import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LoaderProvider } from "@/context/LoaderContext";

const SuisseIntl = localFont({
  src: [
    { path: "./font/SuisseIntl-Regular.ttf", weight: "400", style: "normal" },
    { path: "./font/SuisseIntl-Bold.ttf", weight: "700", style: "bold" },
  ],
  variable: "--font-SuisseIntl",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${SuisseIntl.variable} antialiased font-SuisseIntl`}>
        <LoaderProvider>{children} </LoaderProvider>
      </body>
    </html>
  );
}
